### ISSUE TITLE
Avatar doesn't appear upon account creation

### ISSUE THREAD

**Issue by elazar** [opencfp/opencfp#170] opened 2014-12-11 12:09 UTC
If I specify an avatar when creating a new account, that avatar doesn't appear on my dashboard; in its place is a broken image icon. If, after creating the account, I edit my profile and specify the same image again, it appears as expected.

**Comment by mdwheele** [comment] 2015-03-04 01:32
Was taking a look at this and cannot seem to reproduce the issue on master. If you get a chance, could you try again and if it can be reproduced send any other information that might help?

**Comment by mdwheele** [comment] 2015-06-16 03:48
I can't reproduce this and I've tried all manner of combinations and voodoo to attempt to get it to fail. I'm going to close this out, but if you can reproduce, do comment back and we'll reopen and nail it down.

**Closed by mdwheele** 2015-06-16 03:48 UTC
