### ISSUE TITLE
Unable to insert new OpenCFP\Domain\Entity\TalkTag - Errors: array ( )

### ISSUE THREAD

**Issue by akrabat** [opencfp/opencfp#443] opened 2017-01-17 16:28 UTC
# Steps required to reproduce the problem

1. Try to submit a new talk to https://opencfp.phpkonf.org
2. 
3. 

# Expected Result

* See a thank you page / returned to list (can't remember what the success case is)

# Actual Result

* See a white page with the text `Unable to insert new OpenCFP\Domain\Entity\TalkTag - Errors: array ( )` at the top. 
* Note that the talk appears to have submitted correctly as manually navigating to https://opencfp.phpkonf.org/dashboard shows the talk on the list.

**Comment by anshul35** [comment] 2017-02-02 18:55
Getting the same error! Any ideas on how to fix it?

**Comment by andrewwoods** [comment] 2017-02-07 01:21
I'm getting this too! haven't looked into the cause yet though.

**Comment by chartjes** [comment] 2017-02-13 14:53
Closing because I have removed tags from being part of talks, will eventually add in a migration to drop the impacted tables as well.

**Closed by chartjes** 2017-02-13 14:53 UTC
