### ISSUE TITLE
Don't use auto-incrementing talk submission ids in urls

### ISSUE THREAD

**Issue by michaelcullum** [opencfp/opencfp#303] opened 2015-12-21 11:19 UTC
Otherwise it discloses to talk submitters how many talks have already been submitted. 

https://github.com/ramsey/uuid perhaps?

**Comment by jakefolio** [comment] 2015-12-22 16:08
Is your suggestion to have a secondary ID outside of the PK or to replace PK with a BINARY(16) UUID?

**Comment by mdwheele** [comment] 2015-12-22 22:19
I'm interested in an answer to that question as well as it is a very important distinction to draw. The idea of a surrogate key that isn't the PK for relations is more palatable to me because it will be less risky for existing installs to migrate into. It also could then a matter of per-application configuration (think `app.use_opaque_identifiers` or something).

That said, if we decide to "tack-on" another attribute for purposes of alternative look-up, it will involve a codebase-wide visit to every location that queries by those terms. **If** that is the case, I think we could play double-duty and use it as an opportunity to widen the interface for Talk persistence so that it could do lookups by `AUTO_INCREMENT` identifiers as well as this supposed opaque one. This affords equal access to this data for HTML / JSON views and is a good opportunity to clean up and simplify a bunch of tests.

**Comment by mdwheele** [comment] 2015-12-22 22:30
Then there's always the question of "What purpose / problem are we solving by hiding the number of talks submitted?". There are legitimate reasons to hide internal object identifiers. Generally it's a bad idea TM. In this case, the way it's worded... the request seems more oriented around not accidentally discouraging a Speaker from submitting a Talk because "Why would I send my talk to X conference when they have 300 submissions already?! They'll never accept me!".  Showing a GUID over an integer probably isn't really gonna get rid of that and I bet we could do better towards alleviating that fear through other more powerful means.

**Comment by michaelcullum** [comment] 2015-12-23 22:44
I wasn't suggesting changing the PK, but adding a second key and that key would be used for all interactions on the frontend (API or web-based), so you'd never use or see the auto-incremental ID in urls, or returned as the id for a talk. Also, I'd add that I don't believe Symposium or Pronto (The browser extension) use the opencfp API at all as of yet but I might be mistaken.

@mdwheele When considering the context of the app then yes it is a case of not wanting to put off speakers because a large number, or small number, of talks have been submitted. If it's a large number of talks it can make new speakers think they are unlikely to be accepted (as you pointed out), but the reverse can also happen and I imagine it can also be rather more discouraging if only 100 talks were submitted and none of their 8 submitted talks were selected compared to if there were 800 submissions. I agree that through better... public relations (for lack of a better word)... we can help counter this, but I think that just because there are other solutions to these problems, that doesn't mean we shouldn't consider easy ways to mitigate said problems as well.

But as a more abstracted point, there is currently a config option (https://github.com/opencfp/opencfp/blob/master/config/production.dist.yml#L7) to show the number of submissions, which in it's nature is slightly deceptive as it's still ridiculously easy to see the number of submissions even with this set to false. If we are going to discuss whether or there is a need to add a UUID we should really first discuss the existence of that option, and it being set by default to 'no'.

**Comment by mdwheele** [comment] 2016-01-05 05:41
I think you're right. The option exists only because of an apparent side-comment for a [PR I sent a while back](https://github.com/opencfp/opencfp/pull/184). That PR was about visually indicating that the CFP had ended and @chartjes dropped a suggestion to add the configuration option to disable showing how many talks the CFP ended with. We defaulted to disabled, though I don't remember the conversation actively trying to prevent determining amount of submitted talks. The option seems mostly visually oriented with little semantic meaning outside simply hiding the number on the front page.

That said, it would not be terribly difficult to implement this improvement. If we do, I don't think it should really be configurable; it should default to exposing the opaque surrogate key as the address for any exposed entity. I've confirmed that neither Symposium nor Pronto are using the OpenCFP API, so change of global address should not be any hindrance. If we implement this, we should determine scope as well. Both speaker and talk identifiers, I think, would be in scope. Don't think much else matters.

Another approach to this is to re-think how we respond when a speaker in the system attempts to discover number of submitted talks through resource iteration. Currently, if a speaker attempts to access a talk (view or edit) that is not theirs, they are redirected to the dashboard. If they attempt to view a talk that doesn't exist, they are redirected to the dashboard. Either way, now that I look at it (while I'm writing this) I don't see how a speaker is able to determine number of submitted talks other than their own. Hmm...

That doesn't mean I'm against this improvement (because showing auto increment values isn't the best in the world), but for the purposes of determining number of submitted proposals, I'm missing something I think. @michaelcullum if I am mistaken, could you show me how we're able to determine?

GitHub does pretty much exactly what I've described above for private repository addresses. If it's a private repo and you don't have authorization to read (at least), you get a `404` page rather than some "unauthorized" response. This is done in order to hide information, just as we're attempting to hide number of submitted proposals.

**Comment by chartjes** [comment] 2016-01-14 16:19
Closing -- I don't feel this is a feature that is worth the intrusive changes required to make it work

**Closed by chartjes** 2016-01-14 16:19 UTC
